---
title: "PS3_Yilun_Dai"
output: html_document
---

# Part 1
```{r setup, echo= FALSE, warning=FALSE, message = FALSE}
library(keras)
install_keras(tensorflow = "gpu")

```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
set.seed(1234)
```

## 2. preprocessing data
```{r, echo = FALSE, warning=FALSE, message = FALSE}
mnist <- dataset_mnist()
c(c(train_data, train_labels), c(test_data, test_labels)) %<-% mnist
```


```{r, echo = FALSE, warning=FALSE, message = FALSE}
train_ind <- sample(seq_len(nrow(train_data)), size = 50000)
train_x <- train_data[train_ind, 1:28, 1:28]
test_x <- train_data[-train_ind, 1:28, 1:28 ]
train_y <- train_labels[train_ind]
test_y <- train_labels[-train_ind]

```


```{r, echo = FALSE, warning=FALSE, message = FALSE}
train_x <- array_reshape(train_x, c(50000, 28 * 28))
train_x <- train_x / 255

test_x <- array_reshape(test_x, c(10000, 28 * 28))
test_x <- test_x / 255
```

```{r setup, echo = FALSE, warning=FALSE, message = FALSE}
train_y <- to_categorical(train_y)
test_y <- to_categorical(test_y)
```

## 3. 
```{r setup, echo = FALSE, warning=FALSE, message = FALSE}
network <- keras_model_sequential() %>% 
  layer_dense(units = 512, activation = "relu", kernel_initializer = "normal", input_shape = c(28 * 28)) %>% 
  layer_dense(units = 512, activation = "relu") %>% 
  layer_dense(units = 512, activation = "relu") %>% 
  layer_dense(units = 512, activation = "relu") %>% 
  layer_dense(units = 10, activation = "softmax")
```

```{r setup, echo = FALSE, warning=FALSE, message = FALSE}
network %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)
```

```{r setup, echo = FALSE, warning=FALSE, message = FALSE}
x_train <- array_reshape(train_x, c(50000, 784))
x_test <- array_reshape(test_x, c(10000, 28*28))
networktrain <- network %>% fit(
  x_train,
  train_y,
  epochs = 200,
  batch_size = 512,
  validation_data = list(x_test, test_y), 
  verbose = 2
)

metrics <- network %>% evaluate(x_test, test_y, verbose = 0)
metrics
```

```{r setup}
plot(networktrain)
```

```{r setup, echo = FALSE, warning=FALSE, message = FALSE}

```

